# Generated by Django 6.0.2 on 2026-03-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0002_question_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='duration_minutes',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('in_progress', 'in_progress'), ('closed', 'closed')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='mc_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='mc_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Answer'), ('code', 'Code'), ('multiple_choice', 'Multiple Choice')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='submission',
            name='mc_choice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
